# This project was developed with assistance from AI tools.
{{- if .Values.kueue.enabled }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: isaac-queue
  namespace: {{ include "isaac-mlops.namespace" . }}
  labels:
    {{- include "isaac-mlops.labels" . | nindent 4 }}
spec:
  clusterQueue: {{ .Values.kueue.clusterQueue }}
{{- end }}
