{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-s3-credentials
  namespace: {{ .Values.mlflow.operatorNamespace }}
  labels:
    {{- include "isaac-mlops.labels" . | nindent 4 }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.credentials.user }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.credentials.password }}
---
apiVersion: mlflow.opendatahub.io/v1
kind: MLflow
metadata:
  name: mlflow
  labels:
    {{- include "isaac-mlops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mlflow.replicas }}
  serveArtifacts: true
  artifactsDestination: "s3://mlflow/"
  env:
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://minio.{{ include "isaac-mlops.namespace" . }}.svc:9000"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: mlflow-s3-credentials
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: mlflow-s3-credentials
        key: AWS_SECRET_ACCESS_KEY
  storage:
    accessModes: ["ReadWriteOnce"]
    storageClassName: {{ .Values.storage.storageClassName }}
    resources:
      requests:
        storage: {{ .Values.mlflow.storage.size }}
{{- end }}
