{{- if .Values.ngc.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: ngc-secret
  namespace: {{ include "isaac-mlops.namespace" . }}
  labels:
    {{- include "isaac-mlops.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"nvcr.io":{"username":"$oauthtoken","password":"%s","email":"%s"}}}` .Values.ngc.apiKey .Values.ngc.email | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api-key
  namespace: {{ include "isaac-mlops.namespace" . }}
  labels:
    {{- include "isaac-mlops.labels" . | nindent 4 }}
stringData:
  NGC_API_KEY: {{ .Values.ngc.apiKey | quote }}
{{- end }}
